name: Development

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
  push:
    branches: [ master ]

jobs:
  deploy-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v3

      - name: Setup SSH
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'ubuntu@ec2-44-211-45-56.compute-1.amazonaws.com'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: false
          command: cd /var/www/github_action && ./server_deploy.sh
